travis:
  secure:
    BINSTAR_TOKEN: eJhOGFtaCzSp4MLdU+/7ljb7sCe67HoxfZ35um0v7VOhny9F8y7SOX/B++SAKUgI2GglGWlt4mj7rxKmQxQBd6NHzosAiuOitGBnuY3oiUDkwmxXswLJm/5YLsRaAMTHfpBHC0r0zVtBbB7Cg4r3J+/U27skRiz6BJ5adz4hRW9/uqURWhU9AT2A0RsmipLBUAEoui/Q57WfiWLhk75/skvjQwMaFOPUz+jDjU9pHVu9/gHqX5mZcne4la7Z5NxUsBoKGP2HzZwq8kKr32+VypzMek7pJDpwEVDAETWxfzIVVTvLCzOEB9+3muX5KmRs0X8+YewZwgEbWzgHRAMgzpL7038pNl7MMZF9Zxc6Bl4ZJ/zUV2xcN4y9SMvCKLn4bDp4WXMXv+qxHwx9lfdJLOhmZ0vReXbsZCqKR8Wl6tWN8j11GG30gUqbfVfyw7DCZh0SHXqKEdRPROe7YVV44UQMFvGy/04kHF8x3TaNBTjb9+r7F69bZlEcUliggdseUR45rqtLiyTOaLK57RfKIXXO7zO2FsedYrBarAEmO6jwcCaSWPK2kkb6SxeHX8FHmWdvldbDZvm+bz1j8iN+wvNHWZc3dkoWGjd7xT1A5eiXoeYDHbJyv+yPLC5hB75k8yNX+ku8Zzqi0S75KK5t9lnODQqIl9w4Y2u3qjDQEXU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
